name: Deployment
run-name: ${{ github.actor }} is deploying to Alfa-Hosting 🚀
on:
  push:
    branches: main
jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - run: npm install
      - run: npm run build
      - name: Deploy files via SFTP
        uses: pressidium/lftp-mirror-action@v1
        with:
          # SFTP credentials
          host: ${{ secrets.SERVER }}
          port: 22
          user: ${{ secrets.USERNAME }}
          pass: ${{ secrets.PASSWORD }}
          verifyCertificate: false
          # lftp settings
          onlyNewer: true
          settings: "sftp:auto-confirm=yes"
          # Mirror command options
          localDir: "./dist/"
          remoteDir: "/html/truelsreichardt/"
          reverse: false
